POST http://localhost:5000/api/v1/products
content-type: application/json

{
    "name": "product test 33",
    "price": 20.5,
    "color": "red",
    "size": "X",
    "quantity": 10,
    "image": ["dfgdgfg", "fggffgfgfg"]
}

###
PUT http://localhost:5000/api/v1/products/6238f4cc48385c5fdbb6a25a
content-type: application/json

{
    "image": [""],
    "describtion": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi felis ante, ornare et dignissim sed, cursus ut dolor. Maecenas in gravida purus, a vestibulum metus. Integer tincidunt rutrum velit, vitae condimentum erat pharetra sed. Vivamus tempor nunc id commodo sollicitudin."
}

###
GET http://localhost:5000/api/v1/products

###
GET http://localhost:5000/api/v1/products/623530fd987ef34223dc93c4

###
DELETE http://localhost:5000/api/v1/products/624201914e91752a97d3998a

###
PATCH http://localhost:5000/api/v1/products/rate/623e0c6b4a8b7f02bc6dfbbb
content-type: application/json

{
    "user": "6240a87b1b183019a5b101df",
      "rate": 5,
      "comment": "Quality is not high"
}


###
POST http://localhost:5000/api/v1/users
content-type: application/json

{
    "firstName": "test",
    "lastName": "test",
    "age": 41,
    "email": "test@gmail.com", 
    "password": "test",
    "address": "Hansastrasse 24",
    "country": "Germany",
    "city": "test",
    "phone": "12556"
}

###
POST http://localhost:5000/api/v1/users/login
content-type: application/json

{
    "email": "bmw_x1@yahoo.com", 
    "password": "72111984"
}

###
GET http://localhost:5000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjJmOGE3MGYzNTAwMWU1OGMyOTBjODkiLCJlbWFpbCI6ImJtd194MUB5YWhvby5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NDc2OTcxMzEsImV4cCI6MTY0NzcwMDczMX0.euGiEVNiNw5HhxLrf2VDWCnH_9lj4d-j9GLtDDcJTTY

###
PUT http://localhost:5000/api/v1/users/62432ecacfdbee25025fdebb
content-type: application/json

{
    "firstName": "Jonh",
    "lastName": "Doe",
    "country": "Germany",
    "age": 40,
    "email": "jonhdue@gmail.com" 
}

###
DELETE http://localhost:5000/api/v1/users/624201914e91752a97d3998a

###
GET http://localhost:5000/api/v1/users/623fb36cd5ff3fd78d9bf349

###
PATCH  http://localhost:5000/api/v1/users/621fdd0e0568d118b0bb26f1/product/621ec4a64ce0e143c596f365

###
GET http://localhost:5000/api/v1/image

###
POST http://localhost:5000/api/v1/image
content-type: application/json

{
    "src": ["ghfhgjghfjfgjhfghj", "ssdsdsdsd"]  
}

