POST http://localhost:5000/api/v1/products
content-type: application/json

{
    "name": "product test 12",
    "price": 20.5,
    "size": ["X", "XL", "S", "M"],
    "quantity": 10
}

###
PUT http://localhost:5000/api/v1/products/621ea04b91325c3d3eee13ee
content-type: application/json

{
    "name": "product test2",
    "price": 35,
    "size": ["X", "XS", "XL", "S"],
    "quantity": 5
}

###
GET http://localhost:5000/api/v1/products

###
DELETE http://localhost:5000/api/v1/products/621fb947a0f7e4b268a85ddf

###
POST http://localhost:5000/api/v1/users
content-type: application/json

{
    "firstName": "Jonh",
    "lastName": "Doe",
    "age": 41,
    "email": "jonhdue@gmail.com", 
    "password": "abc12345",
    "address": "Hansastrasse 24"
}

###
POST http://localhost:5000/api/v1/users/login
content-type: application/json

{
    "email": "jonhdue@gmail.com", 
    "password": "abc12345"
}

###
GET http://localhost:5000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjI5Mzk5NzVkMmY1ODhjNDhjZmRmNzAiLCJlbWFpbCI6ImpvbmhkdWVAZ21haWwuY29tIiwiaWF0IjoxNjQ2OTE1OTMxfQ.UNTe0t4q65RTev0VK35v-mVAes9mCDM5ro5GUvMulAU

###
PUT http://localhost:5000/api/v1/users/621ec5467f4cf26235e3c2ce
content-type: application/json

{
    "firstName": "Jonh",
    "lastName": "Doe",
    "age": 40,
    "email": "jonhdue@gmail.com" 
}

###
DELETE http://localhost:5000/api/v1/users/621ec5467f4cf26235e3c2ce

###
PATCH  http://localhost:5000/api/v1/users/621fdd0e0568d118b0bb26f1/product/621ec4a64ce0e143c596f365

###

GET http://localhost:5000/api/v1/image

###
POST http://localhost:5000/api/v1/image
content-type: application/json

{
    "src": ["ghfhgjghfjfgjhfghj", "ssdsdsdsd"]  
}